### ISSUE TITLE
Provider must be supplied

### ISSUE THREAD

**Issue by kevintraver** [zkwentz/ember-simple-auth-firebase#2]
When setting up a brand new ember-cli app following your instructions, I receive the following error:

``` javascript
Error: `provider` must be supplied
```

**Comment by kevintraver** [comment]
I was able to manually pass in provider and it works:

``` javascript
  actions: {
    authenticate: function authenticate(provider) {
      this.get('session').authenticate('authenticator:firebase-simple-auth','firebase-simple-auth',{
        provider: 'password',
        email: this.get('email'),
        password: this.get('password')
      });
    }
  }

```

but it doesn't seem to be coming across from the authenticate method.

Is `provider` something that is supposed coming from ENV?

**Comment by lolmaus** [comment]
It's supposed to come from your template.

Quoting `ember-simple-auth-firebase` readme:

``` hbs
<button {[action 'authenticate' 'password'}}>Login</button>
```

**Comment by herzzanu** [comment]
Just make sure to replace `[` with `{`so it should be 

``` html
<button {{action 'authenticate' 'password'}}>Login</button>
```

**Comment by kevintraver** [comment]
Thanks!
